# Generated by manual fix on 2026-05-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_communitylink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bayan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('speaker', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='communityupdate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='community_updates/'),
        ),
    ]
