# Generated by manual fix on 2026-05-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_bayan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('NIKAH', 'Nikah'), ('BAYAN', 'Bayan'), ('LECTURE', 'Lecture'), ('MEETING', 'Meeting')], max_length=20),
        ),
    ]
