# Generated by manual fix on 2026-05-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_fix_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityupdate',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='community_updates/'),
        ),
    ]
